name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on :
  pull_request: 
  branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acccess it
    -user: actions/checkout@v2
    
    # Runs a single command using the runners shell
    - name: 'Build and Deploy'
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install
    # Runs a set of commands using the runners shell
    - name: 'Authorize'
      run: sfdx force:auth:jwt:grant --clientid=${{ secrets.CONSUMER_KEY }} --username=${{ secrets.USERNAME }} -jwtkeyfile server.key --setdefaultdevhubusername --setalias=hub-org
    - name: 'Convert Metadata'
      run: sfdx force:source:convert --rootdir=force-app -outputdir=convert
    - name: 'Run Test on Metadata'
      run: sfdx force:mdapi:deploy --deploydir=convert --testlevel=RunLocalTests --checkonly -u hub-org
      
    
